language: csharp
sudo: false
dist: trusty
osx_image: xcode8.3
mono: none
dotnet: 2.1.4
os:
  - osx
  - linux

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1


branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

script:
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
    - tools
