image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1

build_script:
  - ps: .\build.ps1 -Target "Appveyor-Build"

test_script:
  - ps: .\build.ps1 -Target "Appveyor-Test"

artifacts:
  - path: 'src\Sandwych.QuickGraph.Core\**\*.nupkg'

deploy:
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: DpUsMQuMOcXRXy74iyC+urW4DQE2o0NyNxe22MhXAg9WdMkDikciAhZgbHTkWsNr
    skip_symbols: true
    artifact: /.*\.nupkg/  

# Build cache
cache:
  - tools -> build.cake
  - packages -> build.cake
